spring:
  application:
    name: producer

  # Kafka producer credentials
  kafka:
    producer:
      bootstrap-servers: localhost:9092

  # Spring cloud Function credentials
  cloud:
    function:
      definition: uppercase
    function.web.path: /uppercase