spring:
  application:
    name: producer
  # Spring cloud Function credentials
  cloud:
    function:
      definition: sendRiderLocation
    stream:
      function:
        definition: sendRiderLocation
      bindings:
        sendRiderLocation-out-0:
          destination: my-topic-new
          content-type: application/json
      poller:
        fixed-delay: 5000
      kafka:
        binder:
          brokers: localhost:9092