spring:
  application:
    name: producer
  # Spring cloud Function credentials
  cloud:
    function:
      definition: sendRiderLocation;sendRiderStatus
    stream:
      function:
        definition: sendRiderLocation
      bindings:
        sendRiderLocation-out-0:
          destination: my-topic
          content-type: application/json
        sendRiderStatus-out-0:
          destination: new-topic
          content-type: text/plain
      poller:
        fixed-delay: 1000
      kafka:
        binder:
          brokers: localhost:9092